<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\avalonia-logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\web_ui\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>web_ui\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3405.78" />
  </ItemGroup>
</Project>
